### ISSUE TITLE
See if the cursor can be a parallel iterator

### ISSUE THREAD

**Issue by buddha314** [marcoscleison/cdo#14]
I don't know if this is possible, but perhaps the returning cursor could be a [parallel iterator](https://chapel-lang.org/docs/master/primers/parIters.html) and we could load matrices quickly.

**Comment by marcoscleison** [comment]
@buddha314 I think that this issue is worth to explore. I have not answer now but I will explore the possibilities.

**Comment by marcoscleison** [comment]
Good news, I have tested parallel iterators for cursor and it is working.
Please, see my example:

https://github.com/marcoscleison/cdo/blob/2042007a083f1140fa29ca06bbaf57bde3b3cdda/examples/parallel.chpl#L55

**Comment by Tshimanga** [comment]
Yep, this worked beautifully. Issue can be closed

**Comment by marcoscleison** [comment]
Thank you!
