### ISSUE TITLE
Forall is acting funny!

### ISSUE THREAD

**Issue by buddha314** [marcoscleison/cdo#16]
Here is a sample, tell me what you think.

```chapel
/*
CREATE AND POPULATE THE TABLE WITH

DROP TABLE IF EXISTS r.cho_named_edges;
CREATE TABLE r.cho_named_edges
(
 from_nm text
, to_nm text
);
INSERT INTO r.cho_named_edges (from_nm, to_nm) VALUES
  ('star lord', 'gamora') , ('star lord', 'groot')
, ('star lord', 'drax') , ('gamora', 'drax')
, ('groot', 'drax') , ('drax', 'rocket')
, ('rocket', 'mantis') , ('mantis', 'yondu')
, ('mantis', 'nebula') , ('yondu', 'nebula')
;


chpl -M/Users/buddha/github/cdo/src/ faerr.chpl


 */
use Cdo, Postgres;

var DB_HOST="localhost",
    DB_USER="buddha",
    DB_PWD="buddha",
    DB_NAME="buddha",
    con = PgConnectionFactory(host=DB_HOST, user=DB_USER, database=DB_NAME, passwd=DB_PWD);

var q = """
SELECT from_nm, to_nm FROM r.cho_named_edges ORDER BY from_nm, to_nm;
""";

var cursor = con.cursor();
cursor.query(q);

/*
 Should return 10 rows
 */
var i: int = 0;
writeln("=== FOR LOOP ===");
for row in cursor {
  writeln("from: ", row['from_nm'], "\tto: ", row['to_nm']);
  i += 1;
}
writeln("Expected 10 rows, got ", i);

var cursor2 = con.cursor();
cursor2.query(q);

/*
 Should also return 10 rows
 */
var j:int = 0;
writeln("\n=== FORALL LOOP ===");
forall row in cursor with (+ reduce j) {
  writeln("from: ", row['from_nm'], "\tto: ", row['to_nm']);
  j += 1;
}
writeln("Expected 10 rows, got ", j);
writeln("Okay, I usually get 9 rows, not 10");
```

Updated with @daviditen  answer to [this SO](https://stackoverflow.com/questions/48771784/how-do-i-count-iterations-in-a-chapel-forall-loop/48772231#48772231)

**Comment by marcoscleison** [comment]
@buddha314 , I sent an example that worked well. I followed the @daviditen suggestion.
Here is the example:
https://github.com/marcoscleison/cdo/blob/cd837690db3ababd02871b7ebe66296d36242071/examples/parallel3.chpl#L20

There was another issue related to ``` cursor.rowcount() ``` method. For Postgres it was returning 1 if the query was a success but with zero rows. Now, it returns the real number of rows. If an error is present it can return -1.

**Comment by buddha314** [comment]
So does this mean `forall row in cursor {}` will now return all 10 rows or did this just fix the `rowcount()`?

**Comment by marcoscleison** [comment]
Here is the example:
https://github.com/marcoscleison/cdo/blob/03ca8cc20436dd771271e75d1b8d0b19a6bddda5/examples/parallel3.chpl#L32

The issue was caused because I considered the Chapel range as inclusive, but the ransge is exclusive. So the forall loop handler was missing one row.
