### ISSUE TITLE
Provide example with variable substitution

### ISSUE THREAD

**Issue by buddha314** [marcoscleison/cdo#3]
Especially for array inserts.  Something like

```
cursor.execute("INSERT INTO public.contacts VALUES (%s, %s)",("email","name"));
```

for both a single row and multiple rows in an array.

**Comment by marcoscleison** [comment]
We can do that in two ways:
1) Loop in the array:
2) Insert method for cursors with arrays.
I will explore both options.

**Comment by marcoscleison** [comment]
I coded a simple insert example for Postgres here:

https://github.com/marcoscleison/cdo/blob/38d66112800a52e1b970d68e154cb88b69871504/examples/insert_pg_ex.chpl#L5

This is only a simple example to play with. 
I am working on table operation abstraction.

**Comment by marcoscleison** [comment]
I provided an approach to insert record into table using cursor: See here:
https://github.com/marcoscleison/cdo/blob/c15343fe491f095ec93ce60597a86ad724e99181/examples/insert_pg_ex.chpl#L27

**Comment by marcoscleison** [comment]
I think that I can close this issue. If you have needed more, feel free to reopen it.
