### ISSUE TITLE
Allow insertion of objects

### ISSUE THREAD

**Issue by buddha314** [marcoscleison/cdo#5]
In [this example](https://github.com/marcoscleison/cdo/blob/38d66112800a52e1b970d68e154cb88b69871504/examples/expq.chpl#L79-L85) you pull a record from a database and create an object from it.  It would be cool to expose the reverse, as in

```
    class MyContact{
        var name:string;
        var email:string;
        proc init(){
            this.name="";
            this.email="";
        }
   }

   var mc = new MyContact();
   mc="MC Hammer";
   mc.email = "stop@hammerti.me";

cur.insert(mc);
```

As I type this, it looks kind of like an [ORM](https://en.wikipedia.org/wiki/Object-relational_mapping) like in [GORM](http://gorm.grails.org/) and might be too big...

**Comment by marcoscleison** [comment]
I am working on that implementation. I think that soon we will have one.
This request is important. That's why I am working with an abstraction such as query builder and Model.
GORM is a good reference. But I will see the capabilities of Chapel.

**Comment by marcoscleison** [comment]
We can insert an object with columns as fields into database.
I sent an example too.
